CREATE ROLE read_only_role NOLOGIN;
CREATE ROLE read_write_role NOLOGIN;
CREATE ROLE app_role NOLOGIN;

GRANT CONNECT ON DATABASE campuslearn TO read_only_role;
GRANT CONNECT ON DATABASE campuslearn TO read_write_role;
GRANT CONNECT ON DATABASE campuslearn TO app_role;

GRANT USAGE ON SCHEMA public TO read_only_role;
GRANT USAGE ON SCHEMA public TO read_write_role;
GRANT USAGE ON SCHEMA public TO app_role;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_only_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO read_write_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO read_only_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO read_write_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_role;
